import React from 'react';

interface PrintReportLayoutProps {
  data: any[];
  kpi: any;
  dateRangeLabel: string;
  generatedBy: string;
}

export const PrintReportLayout = ({ 
  data, 
  kpi, 
  dateRangeLabel, 
  generatedBy 
}: PrintReportLayoutProps) => {
  const formatMoney = (amount: number) => `₵${Number(amount).toFixed(2)}`;

  const getStatusColor = (status: string) => {
    const s = String(status || '').toLowerCase();
    if (s === 'success' || s === 'delivered' || s === 'fulfilled') return 'text-emerald-700 bg-emerald-50 border-emerald-200';
    if (s === 'failed' || s === 'provider_rejected' || s === 'error') return 'text-rose-700 bg-rose-50 border-rose-200';
    return 'text-amber-700 bg-amber-50 border-amber-200';
  };

  return (
    <div id="print-report-layout" className="hidden print:block p-8 bg-white font-sans text-slate-800 w-full">
      {/* STEP 1 & 2 — ENTERPRISE HEADER */}
      <div className="flex border-b-2 border-black pb-4 mb-6">
        <div className="w-[30%] flex flex-col justify-center">
          <h2 className="text-2xl font-black tracking-tighter text-black">DATAPAPA</h2>
          <p className="text-[10px] font-medium text-slate-500">Telecom Intelligence Authority</p>
        </div>
        <div className="w-[40%] flex flex-col items-center justify-center text-center">
          <p className="text-[10px] font-bold text-black uppercase">Premium Internet Data Reseller</p>
          <h1 className="text-sm font-black text-black uppercase tracking-widest my-1">Operational Intelligence Ledger</h1>
          <p className="text-[8px] font-medium text-slate-500">Telecom Fulfillment • Digital Distribution • Real-Time Reporting</p>
        </div>
        <div className="w-[30%] flex flex-col items-end justify-center text-right space-y-0.5">
          <p className="text-[9px] font-semibold">📍 Accra, Greater Accra, Ghana</p>
          <p className="text-[9px] font-medium">✉ support@datapapa.site</p>
          <p className="text-[9px] font-medium">🌐 www.datapapa.site</p>
          <p className="text-[10px] font-bold mt-2">Generated: {new Date().toLocaleString()}</p>
        </div>
      </div>

      {/* STEP 3 — REPORT METADATA */}
      <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 border-l-4 border-black pl-2">Report Metadata</h3>
      <div className="grid grid-cols-3 gap-6 bg-slate-50 p-4 rounded-lg border border-slate-200 mb-6">
        <div>
          <p className="text-[9px] font-bold text-slate-500 uppercase">Report Type</p>
          <p className="text-xs font-semibold">Transaction Intelligence Ledger</p>
        </div>
        <div>
          <p className="text-[9px] font-bold text-slate-500 uppercase">Filter Range</p>
          <p className="text-xs font-semibold">{dateRangeLabel}</p>
        </div>
        <div>
          <p className="text-[9px] font-bold text-slate-500 uppercase">Generated By</p>
          <p className="text-xs font-semibold">{generatedBy}</p>
        </div>
      </div>

      {/* STEP 4 — EXECUTIVE KPI SUMMARY */}
      <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 border-l-4 border-black pl-2">Executive Intelligence Summary</h3>
      <div className="grid grid-cols-4 gap-4 mb-8">
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Total Revenue</p>
          <p className="text-xl font-black text-slate-900">{formatMoney(kpi.totalRevenue)}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Transactions</p>
          <p className="text-xl font-black text-slate-900">{kpi.totalTransactions}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Success Rate</p>
          <p className="text-xl font-black text-slate-900">
            {((kpi.successCount / Math.max(kpi.totalTransactions, 1)) * 100).toFixed(1)}%
          </p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Delivered (OK)</p>
          <p className="text-xl font-black text-emerald-600">{kpi.successCount}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Failed (ERR)</p>
          <p className="text-xl font-black text-rose-600">{kpi.failedCount}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">MTN Volume</p>
          <p className="text-xl font-black text-indigo-600">{kpi.mtnTransactions || 0}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">AirtelTigo Volume</p>
          <p className="text-xl font-black text-indigo-600">{kpi.airtelTigoTransactions || 0}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Telecel Volume</p>
          <p className="text-xl font-black text-indigo-600">{kpi.telecelTransactions || 0}</p>
        </div>
      </div>

      {/* Ledger Table */}
      <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 border-l-4 border-black pl-2">Detailed Transaction Ledger Intelligence</h3>
      <table className="w-full text-left border-collapse text-[10px]">
        <thead>
          <tr className="border-b-2 border-black bg-slate-50">
            <th className="py-3 px-2 font-bold text-black uppercase w-32">Timestamp</th>
            <th className="py-3 px-2 font-bold text-black uppercase w-32">System Ref</th>
            <th className="py-3 px-2 font-bold text-black uppercase w-24">Fulfillment</th>
            <th className="py-3 px-2 font-bold text-black uppercase w-32">Recipient</th>
            <th className="py-3 px-2 font-bold text-black uppercase w-24 text-right">Amount</th>
            <th className="py-3 px-2 font-bold text-black uppercase w-32 pl-4">Delivery</th>
            <th className="py-3 px-2 font-bold text-black uppercase">Provider Ref</th>
          </tr>
        </thead>
        <tbody>
          {data.map((tx, idx) => {
            const displayStatus = tx.vtu_status || tx.status || 'pending';
            return (
              <tr key={tx.id || idx} className="border-b border-slate-200 print:break-inside-avoid">
                <td className="py-3 px-2 font-medium text-slate-600">
                  {new Date(tx.created_at).toLocaleString()}
                </td>
                <td className="py-3 px-2 font-mono font-bold text-slate-900">
                  #{String(tx.id).slice(0,8).toUpperCase()}
                </td>
                <td className="py-3 px-2 font-bold text-slate-700">
                  {String(tx.network).toUpperCase()} {tx.capacity || tx.volume || ''}
                </td>
                <td className="py-3 px-2 font-bold text-slate-600">
                  {tx.recipient_phone || 'N/A'}
                </td>
                <td className="py-3 px-2 font-black text-slate-900 text-right">
                  {Number(tx.amount).toFixed(2)}
                </td>
                <td className="py-3 px-2 pl-4">
                  <span className={`inline-block px-3 py-1 rounded-[4px] text-[8px] font-black uppercase tracking-wider border ${getStatusColor(displayStatus)}`}>
                    {String(displayStatus)}
                  </span>
                </td>
                <td className="py-3 px-2 font-mono text-[9px] text-slate-400">
                  {tx.provider_reference || tx.datahub_reference || 'N/A'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {data.length === 0 && (
        <div className="text-center py-20 text-slate-400 font-bold uppercase tracking-widest text-sm">
          No records found for specified intelligence period.
        </div>
      )}

      {/* Footer */}
      <div className="mt-12 pt-6 border-t font-bold border-slate-200 flex justify-between text-[9px] text-slate-400">
        <div className="space-y-1">
          <p>© {new Date().getFullYear()} Datapapa Intelligence Engine. All Rights Reserved. Confidential Operational Document.</p>
          <p>Generated by Datapapa Operational Intelligence Engine • System Instance: DP-SECURE-NODE-GH</p>
        </div>
        <div className="text-right">
          <p>CLASSIFICATION: ENTERPRISE EXECUTIVE-GRADE INTELLIGENCE</p>
          <p>AUTHENTICATED SYSTEM RECORD</p>
        </div>
      </div>
    </div>
  );
};
