import React from 'react';

interface PrintReportLayoutProps {
  data: any[];
  kpi: any;
  dateRangeLabel: string;
  generatedBy: string;
}

export const PrintReportLayout = ({ data, kpi, dateRangeLabel, generatedBy }: PrintReportLayoutProps) => {
  const formatMoney = (amount: number) => `₵${Number(amount).toFixed(2)}`;

  const getStatusColor = (status: string) => {
    const s = String(status || '').toLowerCase();
    if (s === 'success' || s === 'delivered' || s === 'fulfilled') return 'text-emerald-700 bg-emerald-50 border-emerald-200';
    if (s === 'failed' || s === 'provider_rejected' || s === 'error') return 'text-rose-700 bg-rose-50 border-rose-200';
    return 'text-amber-700 bg-amber-50 border-amber-200';
  };

  return (
    <div id="print-report-layout" className="hidden print:block p-8 bg-white font-sans text-slate-800 w-full">
      {/* Header */}
      <div className="flex justify-between items-end border-b-2 border-slate-200 pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">Transaction Intelligence Ledger</h1>
          <p className="text-sm font-medium text-slate-500 mt-1">Datapapa Operations & Audit Report</p>
        </div>
        <div className="text-right text-xs font-semibold text-slate-500 space-y-1">
          <p>Date Range: <span className="text-slate-800">{dateRangeLabel}</span></p>
          <p>Generated: <span className="text-slate-800">{new Date().toLocaleString()}</span></p>
          <p>Generated By: <span className="text-slate-800">{generatedBy}</span></p>
        </div>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-5 gap-4 mb-8">
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Total Revenue</p>
          <p className="text-xl font-bold text-slate-900">{formatMoney(kpi.totalRevenue)}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Transactions</p>
          <p className="text-xl font-bold text-slate-900">{kpi.totalTransactions}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Success Rate</p>
          <p className="text-xl font-bold text-slate-900">
            {((kpi.successCount / Math.max(kpi.totalTransactions, 1)) * 100).toFixed(1)}%
          </p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Delivered</p>
          <p className="text-xl font-bold text-emerald-600">{kpi.successCount}</p>
        </div>
        <div className="p-4 border border-slate-200 rounded-lg">
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Failed</p>
          <p className="text-xl font-bold text-rose-600">{kpi.failedCount}</p>
        </div>
      </div>

      {/* Ledger Table */}
      <table className="w-full text-left border-collapse text-xs">
        <thead>
          <tr className="border-b-2 border-slate-800">
            <th className="py-3 px-2 font-bold text-slate-700 w-32">Date & Time</th>
            <th className="py-3 px-2 font-bold text-slate-700 w-32">Internal Ref</th>
            <th className="py-3 px-2 font-bold text-slate-700 w-24">Network</th>
            <th className="py-3 px-2 font-bold text-slate-700 w-32">Recipient</th>
            <th className="py-3 px-2 font-bold text-slate-700 w-24 text-right">Amount</th>
            <th className="py-3 px-2 font-bold text-slate-700 w-32 pl-4">Operational Status</th>
            <th className="py-3 px-2 font-bold text-slate-700">Provider Ref</th>
          </tr>
        </thead>
        <tbody>
          {data.map((tx, idx) => {
            const displayStatus = tx.vtu_status || tx.status || 'pending';
            return (
              <tr key={tx.id || idx} className="border-b border-slate-200 print:break-inside-avoid hover:bg-slate-50">
                <td className="py-3 px-2 font-medium text-slate-600">
                  {new Date(tx.created_at).toLocaleString()}
                </td>
                <td className="py-3 px-2 font-mono text-[10px] text-slate-500">
                  {tx.internal_reference || tx.reference || String(tx.id).slice(0,8)}
                </td>
                <td className="py-3 px-2 font-bold text-slate-700">
                  {String(tx.network).toUpperCase()} {tx.capacity || tx.volume || ''}
                </td>
                <td className="py-3 px-2 font-mono text-slate-600">
                  {tx.recipient_phone || 'N/A'}
                </td>
                <td className="py-3 px-2 font-bold text-slate-900 text-right">
                  {formatMoney(tx.amount)}
                </td>
                <td className="py-3 px-2 pl-4">
                  <span className={`inline-block px-2 py-1 rounded-[4px] text-[9px] font-bold uppercase tracking-wider border ${getStatusColor(displayStatus)}`}>
                    {String(displayStatus)}
                  </span>
                </td>
                <td className="py-3 px-2 font-mono text-[10px] text-slate-400 truncate max-w-[150px]">
                  {tx.provider_reference || 'N/A'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {data.length === 0 && (
        <div className="text-center py-12 text-slate-400 font-medium">
          No records found for the selected reporting period.
        </div>
      )}

      {/* Footer */}
      <div className="mt-12 pt-4 border-t border-slate-200 flex justify-between text-[10px] text-slate-400 font-medium">
        <p>CONFIDENTIAL — Datapapa Operational Intelligence</p>
        <p>SYSTEM AUTO-GENERATED LEDGER</p>
      </div>
    </div>
  );
};
