import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register fonts if needed, or use default Helvetica
Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf', fontWeight: 400 },
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI1eMZhrib2Bg-4.ttf', fontWeight: 600 },
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf', fontWeight: 700 }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Inter',
    backgroundColor: '#ffffff'
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    borderBottom: '1 solid #e2e8f0',
    paddingBottom: 20
  },
  headerLeft: {
    flexDirection: 'column'
  },
  headerRight: {
    alignItems: 'flex-end'
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: 4
  },
  subtitle: {
    fontSize: 10,
    color: '#64748b'
  },
  metadata: {
    fontSize: 9,
    color: '#94a3b8',
    marginBottom: 2
  },
  kpiContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    gap: 10
  },
  kpiCard: {
    flex: 1,
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    border: '1 solid #f1f5f9'
  },
  kpiLabel: {
    fontSize: 8,
    color: '#64748b',
    textTransform: 'uppercase',
    marginBottom: 4,
    fontWeight: 600
  },
  kpiValue: {
    fontSize: 16,
    color: '#0f172a',
    fontWeight: 700
  },
  table: {
    width: '100%',
    flexDirection: 'column',
    marginTop: 20
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '1 solid #e2e8f0',
    paddingBottom: 8,
    marginBottom: 8,
    backgroundColor: '#f8fafc',
    padding: 8,
    borderRadius: 4
  },
  tableHeaderCell: {
    fontSize: 8,
    color: '#64748b',
    textTransform: 'uppercase',
    fontWeight: 600
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #f1f5f9',
    paddingVertical: 8,
    paddingHorizontal: 8
  },
  tableCell: {
    fontSize: 9,
    color: '#334155'
  },
  colDate: { width: '15%' },
  colRef: { width: '15%' },
  colNetwork: { width: '12%' },
  colRecipient: { width: '18%' },
  colAmount: { width: '12%' },
  colStatus: { width: '12%' },
  colProvider: { width: '16%' },
  statusBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 8,
    fontWeight: 600,
    alignSelf: 'flex-start'
  },
  statusSuccess: {
    backgroundColor: '#dcfce7',
    color: '#166534'
  },
  statusPending: {
    backgroundColor: '#fef3c7',
    color: '#92400e'
  },
  statusFailed: {
    backgroundColor: '#fee2e2',
    color: '#991b1b'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1 solid #e2e8f0',
    paddingTop: 15
  },
  footerText: {
    fontSize: 8,
    color: '#94a3b8'
  }
});

interface ReportPDFTemplateProps {
  data: any[];
  kpi: any;
  dateRangeLabel: string;
  generatedBy: string;
}

export const ReportPDFTemplate = ({ data, kpi, dateRangeLabel, generatedBy }: ReportPDFTemplateProps) => {
  const formatMoney = (amount: number) => `GHS ${Number(amount).toFixed(2)}`;

  const getStatusStyle = (status: string) => {
    const s = String(status || '').toLowerCase();
    if (s === 'success' || s === 'delivered' || s === 'fulfilled') return styles.statusSuccess;
    if (s === 'failed' || s === 'provider_rejected' || s === 'error') return styles.statusFailed;
    return styles.statusPending;
  };

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            <Text style={styles.title}>Transaction Intelligence Ledger</Text>
            <Text style={styles.subtitle}>Datapapa Operational Reports</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.metadata}>Date Range: {dateRangeLabel}</Text>
            <Text style={styles.metadata}>Generated: {new Date().toLocaleString()}</Text>
            <Text style={styles.metadata}>Generated By: {generatedBy}</Text>
          </View>
        </View>

        <View style={styles.kpiContainer}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total Revenue</Text>
            <Text style={styles.kpiValue}>{formatMoney(kpi.totalRevenue)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Transactions</Text>
            <Text style={styles.kpiValue}>{kpi.totalTransactions}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Success Rate</Text>
            <Text style={styles.kpiValue}>
              {((kpi.successCount / Math.max(kpi.totalTransactions, 1)) * 100).toFixed(1)}%
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Delivered</Text>
            <Text style={styles.kpiValue}>{kpi.successCount}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Failed</Text>
            <Text style={styles.kpiValue}>{kpi.failedCount}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderCell, styles.colDate]}>Date & Time</Text>
            <Text style={[styles.tableHeaderCell, styles.colRef]}>Internal Ref</Text>
            <Text style={[styles.tableHeaderCell, styles.colNetwork]}>Network</Text>
            <Text style={[styles.tableHeaderCell, styles.colRecipient]}>Recipient</Text>
            <Text style={[styles.tableHeaderCell, styles.colAmount]}>Amount</Text>
            <Text style={[styles.tableHeaderCell, styles.colStatus]}>Status</Text>
            <Text style={[styles.tableHeaderCell, styles.colProvider]}>Provider Ref</Text>
          </View>

          {data.slice(0, 50).map((tx, idx) => {
             const displayStatus = tx.vtu_status || tx.status || 'pending';
             return (
              <View key={tx.id || idx} style={styles.tableRow} wrap={false}>
                <Text style={[styles.tableCell, styles.colDate]}>
                  {new Date(tx.created_at).toLocaleString()}
                </Text>
                <Text style={[styles.tableCell, styles.colRef]}>
                  {tx.internal_reference || tx.reference || String(tx.id).slice(0,8)}
                </Text>
                <Text style={[styles.tableCell, styles.colNetwork]}>
                  {String(tx.network).toUpperCase()} {tx.capacity || tx.volume || ''}
                </Text>
                <Text style={[styles.tableCell, styles.colRecipient]}>
                  {tx.recipient_phone || 'N/A'}
                </Text>
                <Text style={[styles.tableCell, styles.colAmount]}>
                  {formatMoney(tx.amount)}
                </Text>
                <View style={styles.colStatus}>
                  <Text style={[styles.statusBadge, getStatusStyle(displayStatus)]}>
                    {String(displayStatus).toUpperCase()}
                  </Text>
                </View>
                <Text style={[styles.tableCell, styles.colProvider]}>
                  {tx.provider_reference || 'N/A'}
                </Text>
              </View>
            );
          })}
          {data.length > 50 && (
            <View style={{ marginTop: 10, alignSelf: 'center' }}>
              <Text style={{ fontSize: 9, color: '#64748b' }}>
                * Showing first 50 transactions of {data.length} total.
              </Text>
            </View>
          )}
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Datapapa Operational Intelligence</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
};
